version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_demo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  tomcat:
    build: .
    container_name: tomcat_demo
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
